#!/usr/bin/env python3

from glob import glob
from socket import gethostname
import json

with open("/vagrant/vagrant/boxes.json") as f:
    boxes = json.load(f)

hostname = gethostname()
with open("/etc/ansible/hosts", "w") as f:
    f.write(f"{hostname:8}  ansible_connection=local\n")
    for name, opts in boxes.items():
        if name == hostname:
            continue
        ipaddr = opts["eth1"]
        keyfiles = glob(f"/vagrant/.vagrant/machines/{name}/parallels/private_key")
        if ipaddr and keyfiles:
            f.write(
                f"{name:8}  ansible_host={ipaddr} ansible_ssh_private_key_file={keyfiles[0]}\n"
            )
